### ISSUE TITLE
Submit to ansible core?

### ISSUE THREAD

**Issue by garbled1** [quinot/ansible-plugin-lookup_ldap#11]
I would really love to see these plugins as part of core ansible.  Any chance you would be willing to submit?  I'd be willing to do the legwork if you just didn't want to deal with the work and approve submission of it.

**Comment by quinot** [comment]
Sure, feel free to submit. It's free software :-)

**Comment by sparunakian** [comment]
Is there any news regarding this issue? Is there an issue in the Ansible repository? If not, I can open one because this lookup is really useful!

**Comment by quinot** [comment]
@sparunakian I do not intend to submit this to Ansible, but if someone else feels like investing the time and effort it would take to get the Ansible team to consider it for integration, they should feel free to do so.

**Comment by sparunakian** [comment]
I've opened an issue in the Ansible repository regarding this: ansible/ansible/issues/34733
