### ISSUE TITLE
TLS Error - Confidentiality expected

### ISSUE THREAD

**Issue by LordAro** [quinot/ansible-plugin-lookup_ldap#14]
Seems like TLS/tls_reqcert is broken, setting tls_reqcert seems to have no effect, it's as if it's not used in the connection object:

```
CONFIDENTIALITY_REQUIRED: {'info': 'TLS confidentiality required', 'desc': 'Confidentiality required'}
```

I can get the same error by removing the -Z from a ldapsearch query

You've got the ldap.set_option(...) stuff, but some searching suggests that some further options are required: https://stackoverflow.com/a/29255727/995325 & https://stackoverflow.com/a/38136255/995325

SSL/ldaps works fine, so I'll workaround with that for now...

**Comment by quinot** [comment]
You are confusing two unrelated things: OPT_X_TLS and OPT_X_TLS_REQUIRE_CERT. As documented, tls_reqcert determines the certificate validation strategy _once a TLS session is established_. This has nothing to do with requiring the use of TLS in the first place.

**Comment by LordAro** [comment]
Ok fine, but TLS isn't happening regardless, with or without the tls_reqcrt parameter and I'm not seeing a way to specify it

**Comment by quinot** [comment]
Right, because there's none currently (except by specifying an ldaps URI, as you found out). We could add another option of course; feel free to submit a patch. But the existing code is correct and behaves consistently with its intent and specification.
