### ISSUE TITLE
plugin returns 'Unexpected error ' when  optional attribute in ldap undefined

### ISSUE THREAD

**Issue by PhilEv** [quinot/ansible-plugin-lookup_ldap#2]
Here is one typical way to illustrate this use case.
# playbook extract:
# [some declaration ]

```
# ldap mode as default+a filter       
- ldap_lookup_config/user_sea:
    filter:  "(uid={{ sea }})"
```
# [some stuff skipped]

```
# the uidNumber is an optional attribute. lookup Will fail for people not having declared one
- name: Direct Lookup query
  debug: msg="{{sea}} {{a_value}} is {{ lookup('ldap', sea , context='user_sea', value="uidNumber") }}"
```
# corresponding output of the playbook run:

for users having a uidNumber set/defined in  ldap it returns:

TASK: [Direct Lookup query] ***************************************************
ok: [127.0.0.1] => {
    "msg": "firstname.lastname@corporate.com uidNumber is 100111111"
}

for users without uidNumber defined yet it returns:

TASK: [Direct Lookup query] ***************************************************
fatal: [127.0.0.1] => Unexpected error in during lookup: 'uidNumber'

Would be great if it returns 'None' in that later  case.

**Comment by PhilEv** [comment]
Thanks,

working well.

2015-03-04 20:25 GMT+01:00 Thomas Quinot notifications@github.com:

**Comment by quinot** [comment]
OK, thanks for the confirmation!
