### ISSUE TITLE
Password is show in clear text mode on debug mode

### ISSUE THREAD

**Issue by MiStErLu** [quinot/ansible-plugin-lookup_ldap#25]
Hi,
 
When we use Ansible Tower or AWX for doing something with ansible and with_ldap
The user password is shown in the console log.
I don't think it's a good idea to show password.

It possible to skip the "bind_pw" keys when we do self._display.vv(....) ?
It's should be very nice :+1: 

Best regards,
MiStErLu

**Comment by quinot** [comment]
Ugh. That's an embarassing bug. Thanks for pointing it out!

**Comment by MiStErLu** [comment]
Thanks  :clap:
