### ISSUE TITLE
Module doesn't work with remote hosts

### ISSUE THREAD

**Issue by elcamlost** [quinot/ansible-plugin-lookup_ldap#8]
Looks like module tries to reach ansible server from localhost, not from the host which runs ansible tasks.

Is there a way to run code on remote machine, as ansible native modules ldap_attr and ldap_entry?

**Comment by quinot** [comment]
This is an Ansible lookup plugin. From http://docs.ansible.com/ansible/latest/playbooks_lookups.html:

> Like all templating, these plugins are evaluated on the Ansible control machine, [...]
